export const artificialAnalysisFixture = {
  status: 200,
  data: [
    {
      id: "aa-gpt-cheap",
      name: "GPT Cheap",
      slug: "gpt-cheap",
      model_creator: { name: "OpenAI", slug: "openai" },
      evaluations: {
        artificial_analysis_intelligence_index: 45,
        artificial_analysis_coding_index: 35,
        ifbench: 0.62,
        tau2: 0.4,
        gdpval_normalized: 0.5,
      },
      median_output_tokens_per_second: 0,
      median_time_to_first_token_seconds: 0,
    },
    {
      id: "aa-gpt-middle",
      name: "GPT Middle",
      slug: "gpt-middle",
      model_creator: { name: "OpenAI", slug: "openai" },
      evaluations: {
        artificial_analysis_intelligence_index: 82,
        artificial_analysis_coding_index: 78,
        terminalbench_hard: 0.72,
        ifbench: 0.91,
        gdpval: 0.76,
      },
      median_output_tokens_per_second: 120,
      median_time_to_first_token_seconds: 1.4,
    },
    {
      id: "aa-gpt-expensive",
      name: "GPT Expensive",
      slug: "gpt-expensive",
      model_creator: { name: "OpenAI", slug: "openai" },
      evaluations: {
        artificial_analysis_intelligence_index: 94,
        artificial_analysis_coding_index: 90,
        terminalbench_hard: 0.86,
        ifbench: 0.96,
        gdpval: 0.9,
      },
      median_output_tokens_per_second: 80,
      median_time_to_first_token_seconds: 2.2,
    },
    {
      id: "aa-gemini-fast",
      name: "Gemini Fast",
      slug: "gemini-fast",
      model_creator: { name: "Google", slug: "google" },
      evaluations: {
        artificial_analysis_intelligence_index: 76,
        tau2_bench_telecom: 0.8,
        ifbench: 0.84,
      },
      median_output_tokens_per_second: 150,
      median_time_to_first_token_seconds: 0.9,
    },
    {
      id: "aa-gemini-lite",
      name: "Gemini 2.0 Flash Lite",
      slug: "gemini-2.0-flash-lite",
      model_creator: { name: "Google", slug: "google" },
      evaluations: {
        artificial_analysis_intelligence_index: 70,
        ifbench: 0.81,
      },
    },
    {
      id: "aa-grok-non-reasoning",
      name: "Grok 4.20 Non Reasoning",
      slug: "grok-4.20-0309-non-reasoning",
      model_creator: { name: "xAI", slug: "xai" },
      evaluations: {
        artificial_analysis_intelligence_index: 88,
        ifbench: 0.9,
      },
      pricing: {
        input: 0.5,
        output: 2,
      },
    },
    {
      id: "aa-grok-multi-agent",
      name: "Grok 4.20 Multi Agent",
      slug: "grok-4.20-multi-agent-0309",
      model_creator: { name: "xAI", slug: "xai" },
      evaluations: {
        artificial_analysis_intelligence_index: 92,
        terminalbench_hard: 0.88,
        ifbench: 0.93,
      },
      price_1m_input_tokens: 0.8,
      price_1m_output_tokens: 4,
    },
    {
      id: "aa-unsupported",
      name: "Unsupported Model",
      slug: "unsupported-model",
      model_creator: { name: "DeepSeek", slug: "deepseek" },
      evaluations: {
        artificial_analysis_intelligence_index: 99,
      },
      pricing: {
        input: 1,
        output: 1,
      },
    },
  ],
};
