export const modelsDevFixture = {
  openai: {
    models: {
      "gpt-5.6": {
        id: "gpt-5.6",
        name: "GPT-5.6",
        family: "gpt-sol",
        attachment: true,
        reasoning: true,
        tool_call: true,
        structured_output: true,
        release_date: "2026-07-09",
        last_updated: "2026-07-09",
        modalities: { input: ["text", "image", "pdf"], output: ["text"] },
        open_weights: false,
        limit: { context: 1_050_000, output: 128_000 },
        cost: { input: 5, output: 30, cache_read: 0.5 },
      },
      "gpt-5.6-sol": {
        id: "gpt-5.6-sol",
        name: "GPT-5.6 Sol",
        family: "gpt-sol",
        reasoning: true,
        tool_call: true,
        structured_output: true,
        release_date: "2026-07-09",
        last_updated: "2026-07-09",
        modalities: { input: ["text", "image"], output: ["text"] },
        open_weights: false,
        limit: { context: 1_050_000, output: 128_000 },
        cost: { input: 5, output: 30 },
      },
      "gpt-realtime-2.1": {
        id: "gpt-realtime-2.1",
        name: "GPT-Realtime-2.1",
        family: "gpt-realtime",
        attachment: true,
        reasoning: true,
        tool_call: true,
        structured_output: false,
        release_date: "2026-07-06",
        last_updated: "2026-07-06",
        modalities: {
          input: ["text", "audio", "image"],
          output: ["text", "audio"],
        },
        open_weights: false,
        limit: { context: 128_000, input: 96_000, output: 32_000 },
        cost: {
          input: 4,
          output: 24,
          cache_read: 0.4,
          input_audio: 32,
          output_audio: 64,
        },
      },
      "gpt-5.5": {
        id: "gpt-5.5",
        name: "GPT-5.5",
        family: "gpt",
        attachment: true,
        reasoning: true,
        tool_call: true,
        structured_output: true,
        release_date: "2026-05-28",
        last_updated: "2026-05-28",
        modalities: { input: ["text", "image"], output: ["text"] },
        open_weights: false,
        limit: { context: 1_050_000, output: 128_000 },
        cost: { input: 5, output: 30 },
      },
    },
  },
  anthropic: {
    models: {
      "claude-opus-5": {
        id: "claude-opus-5",
        name: "Claude Opus 5",
        family: "claude-opus",
        attachment: true,
        reasoning: true,
        tool_call: true,
        structured_output: true,
        release_date: "2026-08-12",
        last_updated: "2026-08-12",
        modalities: { input: ["text", "image", "pdf"], output: ["text"] },
        open_weights: false,
        limit: { context: 1_000_000, output: 128_000 },
        cost: { input: 5, output: 25 },
      },
      "claude-fable-5": {
        id: "claude-fable-5",
        name: "Claude Fable 5",
        family: "claude-fable",
        attachment: true,
        reasoning: true,
        tool_call: true,
        structured_output: true,
        release_date: "2026-06-07",
        last_updated: "2026-06-09",
        modalities: { input: ["text", "image", "pdf"], output: ["text"] },
        open_weights: false,
        limit: { context: 1_000_000, output: 128_000 },
        cost: { input: 10, output: 50, cache_read: 1 },
      },
      "claude-opus-4-8": {
        id: "claude-opus-4-8",
        name: "Claude Opus 4.8",
        family: "claude-opus",
        attachment: true,
        reasoning: true,
        tool_call: true,
        structured_output: true,
        release_date: "2026-07-13",
        last_updated: "2026-07-13",
        modalities: { input: ["text", "image", "pdf"], output: ["text"] },
        open_weights: false,
        limit: { context: 1_000_000, output: 128_000 },
        cost: { input: 5, output: 25 },
      },
      "claude-opus-4-7": {
        id: "claude-opus-4-7",
        name: "Claude Opus 4.7",
        family: "claude-opus",
        attachment: true,
        reasoning: true,
        tool_call: true,
        structured_output: true,
        release_date: "2026-06-24",
        last_updated: "2026-06-24",
        modalities: { input: ["text", "image", "pdf"], output: ["text"] },
        open_weights: false,
        limit: { context: 1_000_000, output: 128_000 },
        cost: { input: 5, output: 25 },
      },
      "claude-opus-4-6": {
        id: "claude-opus-4-6",
        name: "Claude Opus 4.6",
        family: "claude-opus",
        attachment: true,
        reasoning: true,
        tool_call: true,
        structured_output: true,
        release_date: "2026-02-05",
        last_updated: "2026-02-05",
        modalities: { input: ["text", "image", "pdf"], output: ["text"] },
        open_weights: false,
        limit: { context: 1_000_000, output: 128_000 },
        cost: { input: 5, output: 25 },
      },
      "claude-sonnet-5": {
        id: "claude-sonnet-5",
        name: "Claude Sonnet 5",
        family: "claude-sonnet",
        attachment: true,
        reasoning: true,
        tool_call: true,
        structured_output: true,
        release_date: "2026-07-09",
        last_updated: "2026-07-09",
        modalities: { input: ["text", "image", "pdf"], output: ["text"] },
        open_weights: false,
        limit: { context: 1_000_000, output: 128_000 },
        cost: { input: 2, output: 10 },
      },
      "claude-sonnet-4-6": {
        id: "claude-sonnet-4-6",
        name: "Claude Sonnet 4.6",
        family: "claude-sonnet",
        attachment: true,
        reasoning: true,
        tool_call: true,
        structured_output: true,
        release_date: "2026-02-17",
        last_updated: "2026-02-17",
        modalities: { input: ["text", "image", "pdf"], output: ["text"] },
        open_weights: false,
        limit: { context: 1_000_000, output: 128_000 },
        cost: { input: 3, output: 15 },
      },
    },
  },
  xai: {
    models: {
      "grok-4.6": {
        id: "grok-4.6",
        name: "Grok 4.6",
        family: "grok",
        attachment: true,
        reasoning: true,
        tool_call: true,
        structured_output: true,
        release_date: "2026-08-14",
        last_updated: "2026-08-14",
        modalities: { input: ["text", "image", "pdf"], output: ["text"] },
        open_weights: false,
        limit: { context: 500_000, output: 500_000 },
        cost: { input: 2, output: 6 },
      },
      "grok-4.5": {
        id: "grok-4.5",
        name: "Grok 4.5",
        family: "grok",
        attachment: true,
        reasoning: true,
        tool_call: true,
        structured_output: true,
        release_date: "2026-07-08",
        last_updated: "2026-07-08",
        modalities: { input: ["text", "image", "pdf"], output: ["text"] },
        open_weights: false,
        limit: { context: 500_000, output: 500_000 },
        cost: { input: 2, output: 6, cache_read: 0.5 },
      },
    },
  },
  google: {
    models: {
      "gemini-3.7-flash": {
        id: "gemini-3.7-flash",
        name: "Gemini 3.7 Flash",
        family: "gemini",
        reasoning: true,
        release_date: "2026-08-12",
        last_updated: "2026-08-12",
        modalities: { input: ["text", "image"], output: ["text"] },
        open_weights: false,
        limit: { context: 1_000_000, output: 64_000 },
        cost: { input: 0.75, output: 3.75 },
      },
      "gemini-fast": {
        id: "gemini-fast",
        name: "Gemini Fast",
        family: "gemini",
        reasoning: true,
        release_date: "2026-05-01",
        last_updated: "2026-05-01",
        modalities: { input: ["text", "image"], output: ["text"] },
        open_weights: false,
        limit: { context: 1_000_000, output: 64_000 },
        cost: { input: 1, output: 4 },
      },
    },
  },
  moonshotai: {
    models: {
      "kimi-k3": {
        id: "kimi-k3",
        name: "Kimi K3",
        family: "kimi-k3",
        attachment: true,
        reasoning: true,
        tool_call: true,
        structured_output: true,
        release_date: "2026-07-16",
        last_updated: "2026-07-16",
        modalities: {
          input: ["text", "image", "video"],
          output: ["text"],
        },
        open_weights: true,
        limit: { context: 1_048_576, output: 131_072 },
        cost: {},
      },
      "kimi-k2.6": {
        id: "kimi-k2.6",
        name: "Kimi K2.6",
        family: "kimi-k2",
        attachment: true,
        reasoning: true,
        tool_call: true,
        structured_output: true,
        release_date: "2026-06-30",
        last_updated: "2026-06-30",
        modalities: { input: ["text", "image"], output: ["text"] },
        open_weights: true,
        limit: { context: 262_100, output: 65_536 },
        cost: { input: 0.95, output: 4 },
      },
    },
  },
  nvidia: {
    models: {
      "parakeet-tdt-0.6b-v3": {
        id: "parakeet-tdt-0.6b-v3",
        name: "Parakeet TDT 0.6B V3",
        release_date: "2026-01-01",
        last_updated: "2026-01-01",
        modalities: { input: ["audio"], output: ["text"] },
        open_weights: true,
        limit: { context: 0, output: 8_000 },
        cost: {},
      },
    },
  },
  groq: {
    models: {
      "whisper-large-v3-turbo": {
        id: "whisper-large-v3-turbo",
        name: "Whisper Large V3 Turbo",
        family: "whisper",
        release_date: "2025-01-01",
        last_updated: "2026-01-01",
        modalities: { input: ["audio"], output: ["text"] },
        open_weights: false,
        limit: { context: 0, output: 8_000 },
        cost: {},
      },
    },
  },
};

export const artificialAnalysisSpeechToSpeechRecordFixture = {
  id: "voice-high",
  name: "GPT-Realtime-2 (High)",
  shortName: "GPT-Realtime-2 (High)",
  slug: "gpt-realtime-2-high",
  model: { slug: "gpt-realtime-2-high" },
  host: { name: "OpenAI", slug: "openai" },
  s2sQualityIndex: 77.216,
  bbaScore: 0.966,
  tauVoiceAggScore: 0.398,
  tauVoiceScoresByCategory: {
    telecom: { avg_reward: 0.287 },
    retail: { avg_reward: 0.333 },
    airline: { avg_reward: 0.627 },
  },
  fdbScore: 0.953,
  timeToFirstAudioSeconds: 1.14,
  costPerHourOfInputAudio: 4.143,
  pricePerHourInput: 1.152,
  pricePerHourOutput: 4.608,
  defaultSelected: true,
  averageCostPerTask: 0.0214,
};

function speechToSpeechApiModel(input: {
  id: string;
  name: string;
  slug: string;
  creator: string;
  provider: string;
  bba: number;
  tau: number;
  fdb: number;
  inputPrice: number;
  outputPrice: number;
  ttfa: number;
}) {
  return {
    id: input.id,
    name: input.name,
    slug: input.slug,
    model_creator: { id: `${input.provider}-creator`, name: input.creator },
    bba_score: input.bba,
    tau_voice_score: input.tau,
    fdb_score: input.fdb,
    providers: [
      {
        id: `${input.provider}-host`,
        name: input.creator,
        slug: input.provider,
        price_per_hour_input: input.inputPrice,
        price_per_hour_output: input.outputPrice,
        time_to_first_audio_seconds: input.ttfa,
      },
    ],
  };
}

export const artificialAnalysisSpeechToSpeechApiFixture = {
  tier: "pro",
  data: [
    speechToSpeechApiModel({
      id: "voice-high",
      name: "GPT-Realtime-2 (High)",
      slug: "gpt-realtime-2-high",
      creator: "OpenAI",
      provider: "openai",
      bba: 0.966,
      tau: 0.398,
      fdb: 0.953,
      inputPrice: 1.152,
      outputPrice: 4.608,
      ttfa: 1.14,
    }),
    speechToSpeechApiModel({
      id: "voice-cheap",
      name: "GPT Realtime Mini",
      slug: "openai-gpt-realtime-mini",
      creator: "OpenAI",
      provider: "openai",
      bba: 0.64,
      tau: 0.15,
      fdb: 0.95,
      inputPrice: 0.3,
      outputPrice: 1.2,
      ttfa: 0.8,
    }),
    speechToSpeechApiModel({
      id: "voice-medium",
      name: "GPT-Realtime-2 (Medium)",
      slug: "gpt-realtime-2-medium",
      creator: "OpenAI",
      provider: "openai",
      bba: 0.9,
      tau: 0.35,
      fdb: 0.95,
      inputPrice: 1.152,
      outputPrice: 4.608,
      ttfa: 1.4,
    }),
    speechToSpeechApiModel({
      id: "voice-minimal",
      name: "GPT-Realtime-2 (Minimal)",
      slug: "gpt-realtime-2-minimal",
      creator: "OpenAI",
      provider: "openai",
      bba: 0.7,
      tau: 0.3,
      fdb: 0.96,
      inputPrice: 1.152,
      outputPrice: 4.608,
      ttfa: 1,
    }),
    speechToSpeechApiModel({
      id: "voice-google-high",
      name: "Gemini Live (High)",
      slug: "gemini-live-high",
      creator: "Google",
      provider: "google",
      bba: 0.95,
      tau: 0.36,
      fdb: 0.8,
      inputPrice: 0.35,
      outputPrice: 1.4,
      ttfa: 1.3,
    }),
    speechToSpeechApiModel({
      id: "voice-google-minimal",
      name: "Gemini Live (Minimal)",
      slug: "gemini-live-minimal",
      creator: "Google",
      provider: "google",
      bba: 0.7,
      tau: 0.25,
      fdb: 0.75,
      inputPrice: 0.4,
      outputPrice: 1.5,
      ttfa: 0.9,
    }),
    speechToSpeechApiModel({
      id: "voice-xai-high",
      name: "Grok Voice (High)",
      slug: "grok-voice-high",
      creator: "xAI",
      provider: "xai",
      bba: 0.85,
      tau: 0.32,
      fdb: 0.82,
      inputPrice: 0.8,
      outputPrice: 2.5,
      ttfa: 1.1,
    }),
    speechToSpeechApiModel({
      id: "voice-xai-fast",
      name: "Grok Voice (Fast)",
      slug: "grok-voice-fast",
      creator: "xAI",
      provider: "xai",
      bba: 0.75,
      tau: 0.28,
      fdb: 0.78,
      inputPrice: 0.7,
      outputPrice: 2.2,
      ttfa: 0.7,
    }),
  ],
};

const artificialAnalysisSpeechToSpeechPageRecords = [
  artificialAnalysisSpeechToSpeechRecordFixture,
  ...artificialAnalysisSpeechToSpeechApiFixture.data.slice(1).map((model) => {
    const provider = model.providers[0];
    const qualityIndex =
      ((model.bba_score + model.tau_voice_score + model.fdb_score) / 3) * 100;
    return {
      id: model.id,
      name: model.name,
      shortName: model.name,
      slug: model.slug,
      model: { slug: model.slug },
      host: { name: provider.name, slug: provider.slug },
      s2sQualityIndex: qualityIndex,
      bbaScore: model.bba_score,
      tauVoiceAggScore: model.tau_voice_score,
      fdbScore: model.fdb_score,
      timeToFirstAudioSeconds: provider.time_to_first_audio_seconds,
      costPerHourOfInputAudio: provider.price_per_hour_input,
      pricePerHourInput: provider.price_per_hour_input,
      pricePerHourOutput: provider.price_per_hour_output,
      defaultSelected: false,
    };
  }),
];

export const artificialAnalysisSpeechToSpeechPageFixture =
  artificialAnalysisSpeechToSpeechPageRecords
    .map(
      (record) =>
        `<script>self.__next_f.push([1,"${JSON.stringify(record).replaceAll('"', '\\"')}"])</script>`,
    )
    .join("");

export const artificialAnalysisFreeFixture = {
  tier: "free",
  pagination: { page: 1, page_size: 200, total_pages: 1, has_more: false },
  data: [
    {
      id: "aa-fable-5-high",
      name: "Claude Fable 5 (high)",
      slug: "claude-fable-5-high",
      release_date: "2026-06-07",
      model_creator: { name: "Anthropic", slug: "anthropic" },
      evaluations: {
        artificial_analysis_intelligence_index: 91,
        artificial_analysis_agentic_index: 88,
        ifbench: 0.94,
      },
      artificial_analysis_intelligence_index_cost: {
        total_cost: 700,
        cost_per_task: { total_cost: 0.7 },
      },
      pricing: {
        price_1m_input_tokens: 10,
        price_1m_output_tokens: 50,
        price_1m_cache_hit_tokens: 1,
      },
      performance: {
        median_output_tokens_per_second: 92,
        median_time_to_first_token_seconds: 1.1,
      },
    },
    {
      id: "aa-gpt-5-6-sol-high",
      name: "GPT-5.6 Sol (high)",
      slug: "gpt-5-6-sol-high",
      release_date: "2026-07-09",
      model_creator: { name: "OpenAI", slug: "openai" },
      evaluations: {
        artificial_analysis_intelligence_index: 96,
        artificial_analysis_agentic_index: 94,
        ifbench: 0.97,
      },
      artificial_analysis_intelligence_index_cost: {
        total_cost: 800,
        cost_per_task: { total_cost: 0.8 },
      },
      pricing: {
        price_1m_input_tokens: 6,
        price_1m_output_tokens: 36,
      },
      performance: { median_output_tokens_per_second: 80 },
    },
    {
      id: "aa-grok-4-5",
      name: "Grok 4.5",
      slug: "grok-4-5",
      release_date: "2026-07-08",
      model_creator: { name: "xAI", slug: "xai" },
      evaluations: {
        artificial_analysis_intelligence_index: 93,
        artificial_analysis_coding_index: 91,
      },
      pricing: {
        price_1m_input_tokens: 2,
        price_1m_output_tokens: 6,
      },
      performance: { median_output_tokens_per_second: 110 },
    },
  ],
};

export const artificialAnalysisFixture = {
  status: 200,
  data: [
    {
      id: "aa-gpt-cheap",
      name: "GPT Cheap",
      slug: "gpt-cheap",
      model_creator: { name: "OpenAI", slug: "openai" },
      evaluations: {
        artificial_analysis_intelligence_index: 45,
        artificial_analysis_coding_index: 35,
        ifbench: 0.62,
        tau2: 0.4,
        gdpval_normalized: 0.5,
      },
      median_output_tokens_per_second: 0,
      median_time_to_first_token_seconds: 0,
    },
    {
      id: "aa-gpt-middle",
      name: "GPT Middle",
      slug: "gpt-middle",
      model_creator: { name: "OpenAI", slug: "openai" },
      evaluations: {
        artificial_analysis_intelligence_index: 82,
        artificial_analysis_coding_index: 78,
        terminalbench_hard: 0.72,
        ifbench: 0.91,
        gdpval: 0.76,
      },
      median_output_tokens_per_second: 120,
      median_time_to_first_token_seconds: 1.4,
    },
    {
      id: "aa-gpt-expensive",
      name: "GPT Expensive",
      slug: "gpt-expensive",
      model_creator: { name: "OpenAI", slug: "openai" },
      evaluations: {
        artificial_analysis_intelligence_index: 94,
        artificial_analysis_coding_index: 90,
        terminalbench_hard: 0.86,
        ifbench: 0.96,
        gdpval: 0.9,
      },
      median_output_tokens_per_second: 80,
      median_time_to_first_token_seconds: 2.2,
    },
    {
      id: "aa-gemini-fast",
      name: "Gemini Fast",
      slug: "gemini-fast",
      model_creator: { name: "Google", slug: "google" },
      evaluations: {
        artificial_analysis_intelligence_index: 76,
        tau2_bench_telecom: 0.8,
        ifbench: 0.84,
      },
      median_output_tokens_per_second: 150,
      median_time_to_first_token_seconds: 0.9,
    },
    {
      id: "aa-gemini-lite",
      name: "Gemini 2.0 Flash Lite",
      slug: "gemini-2.0-flash-lite",
      model_creator: { name: "Google", slug: "google" },
      evaluations: {
        artificial_analysis_intelligence_index: 70,
        ifbench: 0.81,
      },
    },
    {
      id: "aa-grok-non-reasoning",
      name: "Grok 4.20 Non Reasoning",
      slug: "grok-4.20-0309-non-reasoning",
      model_creator: { name: "xAI", slug: "xai" },
      evaluations: {
        artificial_analysis_intelligence_index: 88,
        ifbench: 0.9,
      },
      pricing: {
        input: 0.5,
        output: 2,
      },
    },
    {
      id: "aa-grok-multi-agent",
      name: "Grok 4.20 Multi Agent",
      slug: "grok-4.20-multi-agent-0309",
      model_creator: { name: "xAI", slug: "xai" },
      evaluations: {
        artificial_analysis_intelligence_index: 92,
        terminalbench_hard: 0.88,
        ifbench: 0.93,
      },
      price_1m_input_tokens: 0.8,
      price_1m_output_tokens: 4,
    },
    {
      id: "aa-unsupported",
      name: "Unsupported Model",
      slug: "unsupported-model",
      model_creator: { name: "DeepSeek", slug: "deepseek" },
      evaluations: {
        artificial_analysis_intelligence_index: 99,
      },
      pricing: {
        input: 1,
        output: 1,
      },
    },
  ],
};

export const artificialAnalysisSpeechToTextFixture = {
  tier: "pro",
  data: [
    {
      id: "stt-openai-mini",
      name: "GPT-4o Mini Transcribe",
      slug: "gpt-4o-mini-transcribe",
      model_creator: { name: "OpenAI", slug: "openai" },
      aa_wer_index: 4,
      aa_agenttalk: 4.4,
      voxpopuli_cleaned_aa: 3.2,
      earnings_22_cleaned_aa: 4.8,
      open_weights: false,
      providers: [
        {
          id: "provider-openai",
          name: "OpenAI",
          slug: "openai",
          price_per_1k_minutes: 3,
          median_speed_factor: 48.36,
          aa_wer_index: 4,
          aa_agenttalk: 4.4,
          voxpopuli_cleaned_aa: 3.2,
          earnings_22_cleaned_aa: 4.8,
        },
      ],
    },
    {
      id: "stt-elevenlabs-scribe-v2",
      name: "Scribe v2",
      slug: "scribe-v2",
      model_creator: { name: "ElevenLabs", slug: "elevenlabs" },
      aa_wer_index: 2.2,
      aa_agenttalk: 2.4,
      voxpopuli_cleaned_aa: 2,
      earnings_22_cleaned_aa: 2.5,
      open_weights: false,
      providers: [
        {
          id: "provider-elevenlabs",
          name: "ElevenLabs",
          slug: "elevenlabs",
          price_per_1k_minutes: 5,
          median_speed_factor: 80,
          aa_wer_index: 2.2,
          aa_agenttalk: 2.4,
          voxpopuli_cleaned_aa: 2,
          earnings_22_cleaned_aa: 2.5,
        },
      ],
    },
    {
      id: "stt-whisper-large-v3-turbo",
      name: "Whisper Large v3 Turbo",
      slug: "whisper-large-v3-turbo",
      model_creator: { name: "OpenAI", slug: "openai" },
      aa_wer_index: 4.6,
      aa_agenttalk: 4.9,
      voxpopuli_cleaned_aa: 4.2,
      earnings_22_cleaned_aa: 4.7,
      open_weights: true,
      providers: [
        {
          id: "provider-groq",
          name: "Groq",
          slug: "groq",
          price_per_1k_minutes: 0.67,
          median_speed_factor: 226.2,
          aa_wer_index: 4.6,
          aa_agenttalk: 4.9,
          voxpopuli_cleaned_aa: 4.2,
          earnings_22_cleaned_aa: 4.7,
        },
      ],
    },
    {
      id: "stt-gemini-2-flash-lite",
      name: "Gemini 2.0 Flash Lite",
      slug: "gemini-2.0-flash-lite",
      model_creator: { name: "Google", slug: "google" },
      aa_wer_index: 3.8,
      providers: [
        {
          id: "provider-google",
          name: "Google",
          slug: "google",
          price_per_1k_minutes: 0.19,
          median_speed_factor: 56.2,
          aa_wer_index: 3.8,
        },
      ],
    },
    {
      id: "stt-nvidia-parakeet",
      name: "Parakeet TDT 0.6B V3",
      slug: "parakeet-tdt-0-6b-v3",
      model_creator: { name: "NVIDIA", slug: "nvidia" },
      aa_wer_index: 4.5,
      aa_agenttalk: 4.7,
      voxpopuli_cleaned_aa: 4.1,
      earnings_22_cleaned_aa: 4.9,
      open_weights: true,
      providers: [
        {
          id: "provider-together",
          name: "Together.ai",
          slug: "togetherai",
          price_per_1k_minutes: 1.5,
          median_speed_factor: 865.2,
          aa_wer_index: 4.5,
          aa_agenttalk: 4.7,
          voxpopuli_cleaned_aa: 4.1,
          earnings_22_cleaned_aa: 4.9,
        },
      ],
    },
    {
      id: "stt-nvidia-missing-price",
      name: "Canary Missing Price",
      slug: "canary-missing-price",
      model_creator: { name: "NVIDIA", slug: "nvidia" },
      aa_wer_index: 5,
      providers: [
        {
          id: "provider-replicate",
          name: "Replicate",
          slug: "replicate",
          median_speed_factor: 120,
        },
      ],
    },
    {
      id: "stt-elevenlabs-missing-wer",
      name: "Scribe Missing WER",
      slug: "scribe-missing-wer",
      model_creator: { name: "ElevenLabs", slug: "elevenlabs" },
      providers: [
        {
          id: "provider-elevenlabs",
          name: "ElevenLabs",
          slug: "elevenlabs",
          price_per_1k_minutes: 2,
          median_speed_factor: 50,
        },
      ],
    },
    {
      id: "stt-unsupported",
      name: "Unsupported STT",
      slug: "unsupported-stt",
      model_creator: { name: "Deepgram", slug: "deepgram" },
      aa_wer_index: 3,
      providers: [
        {
          id: "provider-deepgram",
          name: "Deepgram",
          slug: "deepgram",
          price_per_1k_minutes: 1,
          median_speed_factor: 200,
        },
      ],
    },
  ],
};
