import { normalizeModelsDev, type Catalog } from "../src/registry";

export const modelsDevFixture = {
  openai: {
    models: {
      "gpt-cheap": {
        id: "gpt-cheap",
        name: "GPT Cheap",
        family: "gpt",
        reasoning: false,
        tool_call: true,
        structured_output: true,
        release_date: "2026-01-01",
        last_updated: "2026-01-02",
        modalities: { input: ["text"], output: ["text"] },
        open_weights: false,
        limit: { context: 128000, output: 16000 },
        cost: { input: 0.2, output: 1.2, cache_read: 0.02 },
      },
      "gpt-middle": {
        id: "gpt-middle",
        name: "GPT Middle",
        family: "gpt",
        reasoning: true,
        tool_call: true,
        release_date: "2026-02-01",
        last_updated: "2026-02-02",
        modalities: { input: ["text", "image"], output: ["text"] },
        open_weights: false,
        limit: { context: 400000, output: 64000 },
        cost: { input: 2, output: 8 },
      },
      "gpt-expensive": {
        id: "gpt-expensive",
        name: "GPT Expensive",
        family: "gpt",
        reasoning: true,
        tool_call: true,
        release_date: "2026-03-01",
        last_updated: "2026-03-02",
        modalities: { input: ["text", "image"], output: ["text"] },
        open_weights: false,
        limit: { context: 1000000, output: 128000 },
        cost: { input: 12, output: 60 },
      },
      "text-embedding-3-large": {
        id: "text-embedding-3-large",
        name: "Embedding",
        family: "text-embedding",
        reasoning: false,
        tool_call: false,
        release_date: "2026-04-01",
        last_updated: "2026-04-02",
        modalities: { input: ["text"], output: ["text"] },
        open_weights: false,
        limit: { context: 8192, output: 3072 },
        cost: { input: 0.01, output: 0 },
      },
    },
  },
  google: {
    models: {
      "gemini-fast": {
        id: "gemini-fast",
        name: "Gemini Fast",
        family: "gemini",
        reasoning: true,
        tool_call: true,
        structured_output: true,
        release_date: "2026-02-15",
        last_updated: "2026-02-15",
        modalities: { input: ["text", "image", "pdf"], output: ["text"] },
        open_weights: false,
        limit: { context: 1000000, output: 64000 },
        cost: { input: 0.5, output: 3 },
      },
      "gemma-open": {
        id: "gemma-open",
        name: "Gemma Open",
        family: "gemma",
        reasoning: true,
        tool_call: true,
        structured_output: true,
        release_date: "2026-04-01",
        last_updated: "2026-04-01",
        modalities: { input: ["text", "image"], output: ["text"] },
        open_weights: true,
        limit: { context: 256000, output: 8192 },
        cost: { input: 0, output: 0 },
      },
    },
  },
  xai: {
    models: {
      "grok-fast": {
        id: "grok-fast",
        name: "Grok Fast",
        family: "grok",
        reasoning: true,
        tool_call: true,
        release_date: "2026-01-20",
        last_updated: "2026-01-20",
        modalities: { input: ["text"], output: ["text"] },
        open_weights: false,
        limit: { context: 256000, output: 30000 },
        cost: { input: 0.3, output: 1.5 },
      },
    },
  },
  anthropic: {
    models: {
      "claude-current": {
        id: "claude-current",
        name: "Claude Current",
        family: "claude-sonnet",
        attachment: true,
        reasoning: true,
        tool_call: true,
        release_date: "2026-02-10",
        last_updated: "2026-02-10",
        modalities: { input: ["text", "image"], output: ["text"] },
        open_weights: false,
        limit: { context: 200000, output: 64000 },
        cost: { input: 3, output: 15, cache_write: 3.75 },
      },
      "claude-old": {
        id: "claude-old",
        name: "Claude Old",
        family: "claude",
        reasoning: false,
        tool_call: true,
        status: "deprecated",
        release_date: "2025-01-01",
        last_updated: "2025-01-01",
        modalities: { input: ["text"], output: ["text"] },
        open_weights: false,
        limit: { context: 100000, output: 8000 },
        cost: { input: 1, output: 5 },
      },
    },
  },
  cohere: {
    models: {
      ignored: {
        id: "ignored",
        name: "Ignored",
        family: "command",
        modalities: { input: ["text"], output: ["text"] },
        limit: { context: 1000, output: 1000 },
        cost: { input: 1, output: 1 },
      },
    },
  },
};

export const artificialAnalysisFixture = {
  status: 200,
  data: [
    {
      id: "aa-gpt-cheap",
      name: "GPT Cheap",
      slug: "gpt-cheap",
      model_creator: { name: "OpenAI", slug: "openai" },
      evaluations: {
        artificial_analysis_intelligence_index: 45,
        artificial_analysis_coding_index: 35,
        ifbench: 0.62,
      },
      median_output_tokens_per_second: 180,
      median_time_to_first_token_seconds: 0.8,
    },
    {
      id: "aa-gpt-middle",
      name: "GPT Middle",
      slug: "gpt-middle",
      model_creator: { name: "OpenAI", slug: "openai" },
      evaluations: {
        artificial_analysis_intelligence_index: 82,
        artificial_analysis_coding_index: 78,
        terminalbench_hard: 0.72,
        ifbench: 0.91,
        gdpval: 0.76,
      },
      median_output_tokens_per_second: 120,
      median_time_to_first_token_seconds: 1.4,
    },
    {
      id: "aa-gpt-expensive",
      name: "GPT Expensive",
      slug: "gpt-expensive",
      model_creator: { name: "OpenAI", slug: "openai" },
      evaluations: {
        artificial_analysis_intelligence_index: 94,
        artificial_analysis_coding_index: 90,
        terminalbench_hard: 0.86,
        ifbench: 0.96,
        gdpval: 0.9,
      },
      median_output_tokens_per_second: 80,
      median_time_to_first_token_seconds: 2.2,
    },
    {
      id: "aa-gemini-fast",
      name: "Gemini Fast",
      slug: "gemini-fast",
      model_creator: { name: "Google", slug: "google" },
      evaluations: {
        artificial_analysis_intelligence_index: 76,
        tau2_bench_telecom: 0.8,
        ifbench: 0.84,
      },
      median_output_tokens_per_second: 150,
      median_time_to_first_token_seconds: 0.9,
    },
  ],
};

export function fixtureCatalog(): Catalog {
  return normalizeModelsDev(modelsDevFixture, new Date().toISOString());
}
